feat: shareit - first part
Katibat/java-shareit pull request #1
Opened 2022-07-31 19:16 UTC by Katibat

2022-08-01 16:50 UTC, kukolev requested changes

2022-08-01 16:50 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    ItemService service;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-08-01 16:50 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemStorageImpl.java
> +        if (updateItem.getName() != null && !updateItem.getName().isBlank()) {
Точно ли нужны тут эти проверки? На этих полях повешены аннотации, которые должны валидировать эти поля. Если валидация полей работает, то проверки не нужны.

Аналогично нужно проверить и поправить ниже.

2022-08-01 16:50 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemStorageImpl.java
> +        idCounter += 1;
Этот код можно заменить на idCounter++. По моему так будет проще и понятней.

2022-08-01 16:50 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/UserStorageImpl.java
> +        if (updateUser.getName() != null && !updateUser.getName().isBlank()) {
Точно ли нужны тут эти проверки? На этих полях повешены аннотации, которые должны валидировать эти поля. Если валидация полей работает, то проверки не нужны.

Аналогично нужно проверить и поправить ниже.

2022-08-01 18:42 UTC, Katibat commented on src/main/java/ru/practicum/shareit/item/ItemStorageImpl.java
> +        idCounter += 1;
Исправлено

2022-08-01 18:43 UTC, Katibat commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    ItemService service;
упустила, исправила

2022-08-01 18:57 UTC, Katibat commented on src/main/java/ru/practicum/shareit/item/ItemStorageImpl.java
> +        if (updateItem.getName() != null && !updateItem.getName().isBlank()) {
Нужны, без них не проходят тесты

2022-08-01 18:59 UTC, Katibat commented on src/main/java/ru/practicum/shareit/user/UserStorageImpl.java
> +        if (updateUser.getName() != null && !updateUser.getName().isBlank()) {
да, нужны, иначе тесты не проходят, значит без дополнительных проверок некорректно передаются объекты

2022-08-02 07:37 UTC, kukolev requested changes
Ответил в обсуждении валидации. Нужно настроить валидацию так, чтобы работала.

2022-08-02 07:37 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/UserStorageImpl.java
> +        if (updateUser.getName() != null && !updateUser.getName().isBlank()) {
Это происходит потому что в контроллере UserDto отмечено как `@Validated(Update.class).` Таким образом в ДТО валидируется только email и не валидируется поле name. Дальше ДТО тоже нигде не валидируется и маппится в сущность. Сущность приходит в этот метод с пустыми полями. 

Нужно это поправить - настроить валидацию UserDto или настроить валидацию User при передаче в этот метод.

2022-08-03 11:20 UTC, Katibat commented on src/main/java/ru/practicum/shareit/user/UserStorageImpl.java
> +        if (updateUser.getName() != null && !updateUser.getName().isBlank()) {
Александр, убрала лишние проверки и настроила аннотации. Спасибо за замечания и разъяснения, это важно!

2022-08-03 17:09 UTC, kukolev approved these changes

2022-08-14 07:21 UTC, merged