Add bookings
Katibat/java-shareit pull request #2
Opened 2022-08-18 13:04 UTC by Katibat

2022-08-19 05:35 UTC, kukolev requested changes

2022-08-19 05:35 UTC, kukolev commented on src/main/resources/application.properties
> +#spring.datasource.driverClassName=org.postgresql.Driver
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-19 05:35 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +                .id(null) // null
Задавать поля == null не нужно, т.к. по умолчанию они уже == null у объекта. Также нужно проверить, нет ли тут ошибки, т.к. сущность всего с двумя полями выглядит странно.

2022-08-19 05:35 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (!approved) {
Вместо этого условия можно написать секцию `else {}` к предыдущему. Так код будет немного проще.

2022-08-19 05:35 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        userService.findById(userId);
Здесь результат поиска пользователя никак не используется. Получается, что метод, предназначенный для поиска используется не по назначению. Это лучше переделать - как вариант сделать отдельный метод для проверки и использовать его.

Аналогично нужно поправить ниже.

2022-08-19 06:04 UTC, Katibat commented on src/main/resources/application.properties
> +#spring.datasource.driverClassName=org.postgresql.Driver
Убрала! По заданию нужно было использовать postgresql, а для гит хаб - h2, поэтому оставила закомментированное. А логи мешали искать ошибки.

2022-08-19 06:28 UTC, Katibat commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +                .id(null) // null
null убрала
В тестах постман сущности для создания входят с 3 полями
Например, тест Booking create from user1 to item2 current
{
    "itemId": 2,
    "start": "{{start}}",
    "end": "{{end}}"
}
чтобы получить Item для поля .item(...) нужно подключить к мапперу ItemService или ItemRepository чтобы через метод findById(bookingDtoNew.getItemId) получить объект. Насколько это корректно?

2022-08-19 06:29 UTC, Katibat commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (!approved) {
Исправила

2022-08-19 06:55 UTC, Katibat commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        userService.findById(userId);
Эта строка выполняет функцию проверки, если ее убрать, то упадут тесты Booking get all for wrong user и Booking get all for wrong owner user, в которые передаются несуществующие пользователи. 
Метод userService.findById(userId) в случае, если пользователь не найден, выкидывает обработанную ошибку 404

public User findById(Long userId) {
        return repository.findById(userId)
                .orElseThrow(() -> new NotFoundException("Не найден пользователь с идентификатором № " + userId));
    }

2022-08-19 16:46 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        userService.findById(userId);
Да, я это понимаю, но проблема в том, что это поведение не очевидно. Логичнее было бы сделать другой метод и вызвать его - checkIsUserExists. Метод можно было бы сделать с использованием EXIST из SQL.

2022-08-19 16:57 UTC, kukolev requested changes

2022-08-19 16:57 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        addComments(itemDto);
Это бизнес-логика, место которой в сервисе. Нужно перенести в сервис.

2022-08-19 16:57 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        itemList.forEach(this::addLastAndNextBooking);
Это бизнес-логика, место которой в сервисе. Нужно перенести в сервис.

2022-08-21 10:03 UTC, Katibat commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        userService.findById(userId);
Добавила стандартный метод JpaRepository existsById() для проверки пользователя

2022-08-22 13:42 UTC, Katibat commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        addComments(itemDto);
Перенесла!

2022-08-22 13:42 UTC, Katibat commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        itemList.forEach(this::addLastAndNextBooking);
Выполнено

2022-08-22 21:13 UTC, kukolev approved these changes

2022-08-24 06:56 UTC, merged