feat: gateway, server, bd
Katibat/java-shareit pull request #4
Opened 2022-09-12 07:13 UTC by Katibat

2022-09-13 16:51 UTC, kukolev requested changes

2022-09-13 16:51 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookItemRequestDto.java
> +	private long itemId;
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-09-13 16:51 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookingState.java
> +	// Все
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-09-13 16:51 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +    private <T> ResponseEntity<Object> makeAndSendRequest(HttpMethod method, String path, Long userId, @Nullable Map<String, Object> parameters, @Nullable T body) {
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-09-13 16:51 UTC, kukolev commented on server/pom.xml
> +	<modelVersion>4.0.0</modelVersion>
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-09-13 17:51 UTC, Katibat commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookItemRequestDto.java
> +	private long itemId;
исправлено

2022-09-13 17:53 UTC, Katibat commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookingState.java
> +	// Все
исправлено

2022-09-13 17:56 UTC, Katibat commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +    private <T> ResponseEntity<Object> makeAndSendRequest(HttpMethod method, String path, Long userId, @Nullable Map<String, Object> parameters, @Nullable T body) {
исправлено

2022-09-13 17:58 UTC, Katibat commented on server/pom.xml
> +	<modelVersion>4.0.0</modelVersion>
исправлено

2022-09-14 07:13 UTC, kukolev requested changes

2022-09-14 07:13 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/ShareItGateway.java
> +	public static void main(String[] args) {
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-09-14 11:34 UTC, Katibat commented on gateway/src/main/java/ru/practicum/shareit/ShareItGateway.java
> +	public static void main(String[] args) {
исправлено и в классе ShareitServer тоже

2022-09-14 16:07 UTC, kukolev approved these changes

2022-09-17 13:03 UTC, merged